[Application Options]
debuglevel=info
bitcoin.active=true
bitcoin.node=bitcoind

[Bitcoin]
bitcoin.regtest=true

[Bitcoind]
bitcoind.rpchost=bitcoind:18443
bitcoind.rpcuser=user
bitcoind.rpcpass=pass
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333

[LND]
nolisten=false
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
tlsextraip=0.0.0.0
no-macaroons=false